import { contextBridge, ipcRenderer } from 'electron'
import { IPC } from '../shared/types'
import type { WorkdeskApi, HarnessStatus } from '../shared/types'

function subscribe<T>(channel: string, cb: (payload: T) => void): () => void {
  const listener = (_e: unknown, payload: T): void => cb(payload)
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}

const api: WorkdeskApi = {
  ping: () => Promise.resolve('pong'),
  configGet: () => ipcRenderer.invoke(IPC.configGet),
  configSet: (patch) => ipcRenderer.invoke(IPC.configSet, patch),
  harnessGetStatus: () => ipcRenderer.invoke(IPC.harnessGetStatus),
  harnessStart: () => ipcRenderer.invoke(IPC.harnessStart),
  harnessStop: () => ipcRenderer.invoke(IPC.harnessStop),
  harnessRestart: () => ipcRenderer.invoke(IPC.harnessRestart),
  harnessGetLogs: () => ipcRenderer.invoke(IPC.harnessGetLogs),
  onHarnessStatusChanged: (cb) => subscribe<HarnessStatus>(IPC.harnessStatusChanged, cb),
  onHarnessLog: (cb) => subscribe<string>(IPC.harnessLog, cb),
  githubGetStatus: () => ipcRenderer.invoke(IPC.githubGetStatus),
  githubSetToken: (token) => ipcRenderer.invoke(IPC.githubSetToken, token),
  githubVerifyToken: (token) => ipcRenderer.invoke(IPC.githubVerifyToken, token),
  githubClearToken: () => ipcRenderer.invoke(IPC.githubClearToken),
  githubListRepos: (kind) => ipcRenderer.invoke(IPC.githubListRepos, kind),
  githubSearchRepos: (q) => ipcRenderer.invoke(IPC.githubSearchRepos, q),
  githubGetRepo: (owner, repo) => ipcRenderer.invoke(IPC.githubGetRepo, owner, repo),
  githubGetContents: (owner, repo, path) => ipcRenderer.invoke(IPC.githubGetContents, owner, repo, path),
  githubListIssues: (owner, repo, state) => ipcRenderer.invoke(IPC.githubListIssues, owner, repo, state),
  githubGetIssue: (owner, repo, number) => ipcRenderer.invoke(IPC.githubGetIssue, owner, repo, number),
  githubListPulls: (owner, repo, state) => ipcRenderer.invoke(IPC.githubListPulls, owner, repo, state),
  githubGetPull: (owner, repo, number) => ipcRenderer.invoke(IPC.githubGetPull, owner, repo, number),
  githubListCommits: (owner, repo) => ipcRenderer.invoke(IPC.githubListCommits, owner, repo),
  githubGetCommit: (owner, repo, sha) => ipcRenderer.invoke(IPC.githubGetCommit, owner, repo, sha),
  githubSaveFile: (owner, repo, path, content, message, sha) => ipcRenderer.invoke(IPC.githubSaveFile, owner, repo, path, content, message, sha),
  githubDeleteFile: (owner, repo, path, message, sha) => ipcRenderer.invoke(IPC.githubDeleteFile, owner, repo, path, message, sha),
  githubUploadFile: (owner, repo, path, contentBase64, message, sha) => ipcRenderer.invoke(IPC.githubUploadFile, owner, repo, path, contentBase64, message, sha),
  githubDownloadFile: (owner, repo, path, destPath) => ipcRenderer.invoke(IPC.githubDownloadFile, owner, repo, path, destPath),
  githubPickSavePath: (defaultName) => ipcRenderer.invoke(IPC.githubPickSavePath, defaultName),
  githubGetReadme: (owner, repo) => ipcRenderer.invoke(IPC.githubGetReadme, owner, repo),
  githubListTree: (owner, repo, dirPath) => ipcRenderer.invoke(IPC.githubListTree, owner, repo, dirPath),
  githubDownloadFiles: (owner, repo, paths, destDir) => ipcRenderer.invoke(IPC.githubDownloadFiles, owner, repo, paths, destDir),
  githubPickSaveDir: () => ipcRenderer.invoke(IPC.githubPickSaveDir),
  onGithubDownloadProgress: (cb) => subscribe<{ done: number; total: number }>(IPC.githubDownloadProgress, cb),
  githubCommitFiles: (owner, repo, message, files) => ipcRenderer.invoke(IPC.githubCommitFiles, owner, repo, message, files),
  githubPickFiles: () => ipcRenderer.invoke(IPC.githubPickFiles),
  githubPickFolder: () => ipcRenderer.invoke(IPC.githubPickFolder),
  githubScanUpload: (localPaths, mode, baseRepoDir) => ipcRenderer.invoke(IPC.githubScanUpload, localPaths, mode, baseRepoDir),
  githubUploadBatch: (owner, repo, message, files) => ipcRenderer.invoke(IPC.githubUploadBatch, owner, repo, message, files),
  onGithubUploadProgress: (cb) => subscribe<{ done: number; total: number }>(IPC.githubUploadProgress, cb),
  statsGet: () => ipcRenderer.invoke(IPC.statsGet),
  statsReset: () => ipcRenderer.invoke(IPC.statsReset),
  statsSetBucket: (bucket, ctx) => ipcRenderer.invoke(IPC.statsSetBucket, bucket, ctx),
  statsBump: (field, by) => ipcRenderer.invoke(IPC.statsBump, field, by),
  statsBumpMap: (field, key, by) => ipcRenderer.invoke(IPC.statsBumpMap, field, key, by),
  gitClone: (url) => ipcRenderer.invoke(IPC.gitClone, url),
  backupCreate: (destPath) => ipcRenderer.invoke(IPC.backupCreate, destPath),
  backupRestore: (srcPath) => ipcRenderer.invoke(IPC.backupRestore, srcPath),
  openExternal: (url) => ipcRenderer.invoke(IPC.appOpenExternal, url),
  translate: (text) => ipcRenderer.invoke(IPC.appTranslate, text),
  ideOpenFiles: () => ipcRenderer.invoke(IPC.ideOpenFiles),
  ideOpenFolder: () => ipcRenderer.invoke(IPC.ideOpenFolder),
  ideSaveFileDialog: (defaultName) => ipcRenderer.invoke(IPC.ideSaveFileDialog, defaultName),
  ideReadFile: (path) => ipcRenderer.invoke(IPC.ideReadFile, path),
  ideListDir: (path) => ipcRenderer.invoke(IPC.ideListDir, path),
  ideWriteFile: (path, content, encoding) => ipcRenderer.invoke(IPC.ideWriteFile, path, content, encoding),
  ideDeleteFile: (path) => ipcRenderer.invoke(IPC.ideDeleteFile, path),
  ideRenameFile: (oldPath, newName) => ipcRenderer.invoke(IPC.ideRenameFile, oldPath, newName),
  idePickImage: () => ipcRenderer.invoke(IPC.idePickImage),
  ideSaveCustomWallpaper: (src) => ipcRenderer.invoke(IPC.ideSaveCustomWallpaper, src),
  ideDetectTools: () => ipcRenderer.invoke(IPC.ideDetectTools),
  ideRun: (req) => ipcRenderer.invoke(IPC.ideRun, req),
  ideCompile: (req) => ipcRenderer.invoke(IPC.ideCompile, req),
  ideRunTemp: (fileName) => ipcRenderer.invoke(IPC.ideRunTemp, fileName),
  aiAsk: (req) => ipcRenderer.invoke(IPC.aiAsk, req),
  aiListModels: () => ipcRenderer.invoke(IPC.aiListModels),
  quitReal: () => ipcRenderer.invoke(IPC.appQuitReal),
  showWindow: () => ipcRenderer.invoke(IPC.appShowWindow),
  onNavigate: (cb) => subscribe<string>(IPC.appNavigate, cb),
  getVersion: () => ipcRenderer.invoke(IPC.appGetVersion)
}

contextBridge.exposeInMainWorld('api', api)
